version: '3.8'

services:
  db:
    image: postgres:14-alpine

    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: LINK_TREE

    ports:
      - 5432:5432
