# Generated by Django 5.2.1 on 2025-06-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
